name: vcnet12-aircraft-fs
train_dataset: aircraft-fs
train_dataset_args: {split: train, aug: lee}
val_dataset: aircraft-fs
val_dataset_args: {split: val, aug: lee}

fs_dataset_train: aircraft-fs
fs_dataset_train_args: {split: train, aug: lee}
fs_dataset_val: aircraft-fs
fs_dataset_val_args: {split: val, aug: lee}

model: VCRNet
model_args:
    encoder: encoder-vcnet12
    encoder_args:  {
        use_region_sensing_list: [False, True, False],
        use_self_attention_list: [False, True, False],
        use_pixel_level_sensing_list: [False, False, True],
    }
    classifier: linear-classifier 
    classifier_args: {n_classes: 50}
    sideout_info: []

train_branch_1: True
train_branch_2: True
eval_val: True
eval_fs: True

# classification hyperparameters
batch_size: 64
max_epoch: 60

# few-shot hyperparameters
n_way: 5
n_shot: 1
n_train_shot: 5
n_query: 15
train_batches: 1000 # 1000
ep_per_batch: 1

opt: lee
save_epoch: 5