name: vcnet4-stanford-car
train_dataset: stanford-car
train_dataset_args: {split: train, aug: lee}
val_dataset: stanford-car
val_dataset_args: {split: val, aug: lee}

fs_dataset_train: stanford-car
fs_dataset_train_args: {split: train, aug: lee}
fs_dataset_val: stanford-car
fs_dataset_val_args: {split: val, aug: lee}

model: VCRNet
model_args:
    encoder: encoder-vcnet4
    encoder_args:  {
        use_region_sensing_list: [False, True, False],
        use_self_attention_list: [False, True, False],
        use_pixel_level_sensing_list: [False, False, True],
    }
    classifier: linear-classifier 
    classifier_args: {n_classes: 130}
    sideout_info: []

train_branch_1: True
train_branch_2: True
eval_val: True
eval_fs: True

# classification hyperparameters
batch_size: 64
max_epoch: 60

# few-shot hyperparameters
n_way: 10
n_shot: 1
n_train_shot: 5
n_query: 15
train_batches: 1000 # 1000
ep_per_batch: 2

opt: lee
# opt: adam
save_epoch: 5